name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: gelogonza
          outputs: |
            output/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: output/github-contribution-grid-snake.svg
      - name: Push generated Snake
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
